name: Release Version

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build
        run: dotnet build -c Release

      - name: Pack
        run: dotnet pack ./Bank.Domain/Bank.Domain.csproj -c Release -o out

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Versión 1.0.${{ github.run_number }}
          files: out/*.nupkg
